sudo: required

language: python

services:
  - docker

install:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml build react
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml build django

before_script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d db && sleep 10

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run react npm run test -- --coverage
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run react npm run lint
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml run django ./manage.py test
